name: Tecton CI
on:
  workflow_dispatch:
jobs:
  setup-tecton:
    runs-on: ubuntu-latest
    env:
      TECTON_API_KEY: ${{ secrets.TECTON_API_KEY }}
      API_SERVICE: https://spark.tecton.ai/api  # Update this to your cluster
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.9"
      - name: Install Tecton CLI
        run: pip install tecton
      - name: Login to Tecton
        run: tecton login spark.tecton.ai
      - name: Create workspace
        run: tecton workspace create CS-6947-1
      - name: Select workspace
        run: tecton workspace select CS-6947-1
