name: Tecton CI
on:
  workflow_dispatch:
jobs:
  stress-test-1:
    runs-on: ubuntu-latest
    env:
      TECTON_API_KEY: ${{ secrets.TECTON_API_KEY }}
      API_SERVICE: https://spark.tecton.ai/api  # Update this to your cluster
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.9"
      - name: Install Tecton CLI
        run: pip install tecton
      - name: Create workspace
        run: tecton workspace create temp-deployment-dev-workspace-1
      - name: Select workspace
        run: tecton workspace select temp-deployment-dev-workspace-1
      - name: Tecton init
        run: tecton init
      - name: Tecton plan
        run: tecton plan
      - name: Tecton apply
        run: tecton apply
      - name: Delete workspace
        run: tecton workspace delete temp-deployment-dev-workspace-1 -y

  stress-test-2:
    runs-on: ubuntu-latest
    env:
      TECTON_API_KEY: ${{ secrets.TECTON_API_KEY }}
      API_SERVICE: https://spark.tecton.ai/api  # Update this to your cluster
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.9"
      - name: Install Tecton CLI
        run: pip install tecton
      - name: Create workspace
        run: tecton workspace create temp-deployment-dev-workspace-2
      - name: Select workspace
        run: tecton workspace select temp-deployment-dev-workspace-2
      - name: Tecton init
        run: tecton init
      - name: Tecton plan
        run: tecton plan
      - name: Tecton apply
        run: tecton apply
      - name: Delete workspace
        run: tecton workspace delete temp-deployment-dev-workspace-2 -y

